version: "3.0"
services:

  database:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store
    ports:
      - "3307:3306"
    volumes:
      - ./sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql

  store:
    image: store
    restart: on-failure
    depends_on:
      - database
    ports:
      - "8081:8081"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=store
      - DATABASE_PORT=3306